version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: movierec-db
    environment:
      POSTGRES_DB: movierec
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
