spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movierec
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

tmdb:
  api:
    key: sua_chave_api
